#!/usr/bin/bash
#SBATCH -A hostphylumpred
#SBATCH -p plgrid
#SBATCH --time=3-00:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=12
#SBATCH --mem=12GB

subdir="ga_res/knn/1"
infile="$SCRATCHDIR/datasets/splits.dump"
mkdir $SCRATCHDIR/datasets
mkdir -p $SCRATCHDIR/$subdir
mkdir -p $SLURM_SUBMIT_DIR/$subdir
cp $SLURM_SUBMIT_DIR/datasets/splits.dump $SCRATCHDIR/datasets
module load plgrid/tools/python/2.7.13
python code/knn_ga_feature_selection.py 10 5 cxUniform 0.1 4 1 3 100 2 $SCRATCHDIR/$subdir --infile $infile --cpus 12
mv $SCRATCHDIR/$subdir/10_5_cxUniform_0.1_4_1_100_3_2 $SLURM_SUBMIT_DIR/
python code/knn_ga_feature_selection.py 10 5 cxUniform 0.1 4 1 3 100 2 $SCRATCHDIR/$subdir --infile $infile --cpus 6
rm $SCRATCHDIR/$subdir/10_5_cxUniform_0.1_4_1_100_3_2
python code/knn_ga_feature_selection.py 10 5 cxUniform 0.1 4 1 3 100 2 $SCRATCHDIR/$subdir --infile $infile --cpus 2
rm $SCRATCHDIR/$subdir/10_5_cxUniform_0.1_4_1_100_3_2
python code/knn_ga_feature_selection.py 10 5 cxUniform 0.1 4 1 3 100 2 $SCRATCHDIR/$subdir --infile $infile --cpus 1
rm $SCRATCHDIR/$subdir/10_5_cxUniform_0.1_4_1_100_3_2

